# Generated by Django 6.0.3 on 2026-03-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.TextField()),
                ('CourseTitle', models.TextField()),
                ('Instructor', models.TextField()),
            ],
        ),
    ]
